# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import flowforge_pb2 as flowforge__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in flowforge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub(object):
    """TaskService handles task status updates from SDK
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateStatus = channel.unary_unary(
                '/flowforge.v1.TaskService/UpdateStatus',
                request_serializer=flowforge__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=flowforge__pb2.UpdateStatusResponse.FromString,
                _registered_method=True)
        self.SetOutput = channel.unary_unary(
                '/flowforge.v1.TaskService/SetOutput',
                request_serializer=flowforge__pb2.SetOutputRequest.SerializeToString,
                response_deserializer=flowforge__pb2.SetOutputResponse.FromString,
                _registered_method=True)
        self.SaveCheckpoint = channel.unary_unary(
                '/flowforge.v1.TaskService/SaveCheckpoint',
                request_serializer=flowforge__pb2.SaveCheckpointRequest.SerializeToString,
                response_deserializer=flowforge__pb2.SaveCheckpointResponse.FromString,
                _registered_method=True)
        self.GetCheckpoint = channel.unary_unary(
                '/flowforge.v1.TaskService/GetCheckpoint',
                request_serializer=flowforge__pb2.GetCheckpointRequest.SerializeToString,
                response_deserializer=flowforge__pb2.GetCheckpointResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_unary(
                '/flowforge.v1.TaskService/StreamLogs',
                request_serializer=flowforge__pb2.LogEntry.SerializeToString,
                response_deserializer=flowforge__pb2.StreamLogsResponse.FromString,
                _registered_method=True)


class TaskServiceServicer(object):
    """TaskService handles task status updates from SDK
    """

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCheckpoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=flowforge__pb2.UpdateStatusRequest.FromString,
                    response_serializer=flowforge__pb2.UpdateStatusResponse.SerializeToString,
            ),
            'SetOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SetOutput,
                    request_deserializer=flowforge__pb2.SetOutputRequest.FromString,
                    response_serializer=flowforge__pb2.SetOutputResponse.SerializeToString,
            ),
            'SaveCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCheckpoint,
                    request_deserializer=flowforge__pb2.SaveCheckpointRequest.FromString,
                    response_serializer=flowforge__pb2.SaveCheckpointResponse.SerializeToString,
            ),
            'GetCheckpoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCheckpoint,
                    request_deserializer=flowforge__pb2.GetCheckpointRequest.FromString,
                    response_serializer=flowforge__pb2.GetCheckpointResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=flowforge__pb2.LogEntry.FromString,
                    response_serializer=flowforge__pb2.StreamLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'flowforge.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('flowforge.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService(object):
    """TaskService handles task status updates from SDK
    """

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowforge.v1.TaskService/UpdateStatus',
            flowforge__pb2.UpdateStatusRequest.SerializeToString,
            flowforge__pb2.UpdateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowforge.v1.TaskService/SetOutput',
            flowforge__pb2.SetOutputRequest.SerializeToString,
            flowforge__pb2.SetOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowforge.v1.TaskService/SaveCheckpoint',
            flowforge__pb2.SaveCheckpointRequest.SerializeToString,
            flowforge__pb2.SaveCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCheckpoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/flowforge.v1.TaskService/GetCheckpoint',
            flowforge__pb2.GetCheckpointRequest.SerializeToString,
            flowforge__pb2.GetCheckpointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/flowforge.v1.TaskService/StreamLogs',
            flowforge__pb2.LogEntry.SerializeToString,
            flowforge__pb2.StreamLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
