// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: pkg/api/proto/flowforge.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Details       string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"` // JSON string
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateStatusRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateStatusRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStatusRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateStatusRequest) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *UpdateStatusRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *UpdateStatusRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputRequest) Reset() {
	*x = SetOutputRequest{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputRequest) ProtoMessage() {}

func (x *SetOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutputRequest.ProtoReflect.Descriptor instead.
func (*SetOutputRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{2}
}

func (x *SetOutputRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SetOutputRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SetOutputRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetOutputRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetOutputResponse) Reset() {
	*x = SetOutputResponse{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutputResponse) ProtoMessage() {}

func (x *SetOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutputResponse.ProtoReflect.Descriptor instead.
func (*SetOutputResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{3}
}

func (x *SetOutputResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SaveCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"` // JSON string
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCheckpointRequest) Reset() {
	*x = SaveCheckpointRequest{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointRequest) ProtoMessage() {}

func (x *SaveCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointRequest.ProtoReflect.Descriptor instead.
func (*SaveCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{4}
}

func (x *SaveCheckpointRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SaveCheckpointRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SaveCheckpointRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *SaveCheckpointRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCheckpointResponse) Reset() {
	*x = SaveCheckpointResponse{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCheckpointResponse) ProtoMessage() {}

func (x *SaveCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCheckpointResponse.ProtoReflect.Descriptor instead.
func (*SaveCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{5}
}

func (x *SaveCheckpointResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointRequest) Reset() {
	*x = GetCheckpointRequest{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointRequest) ProtoMessage() {}

func (x *GetCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{6}
}

func (x *GetCheckpointRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetCheckpointRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // JSON string, empty if no checkpoint
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCheckpointResponse) Reset() {
	*x = GetCheckpointResponse{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointResponse) ProtoMessage() {}

func (x *GetCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointResponse.ProtoReflect.Descriptor instead.
func (*GetCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{7}
}

func (x *GetCheckpointResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetCheckpointResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	LineNum       int32                  `protobuf:"varint,7,opt,name=line_num,json=lineNum,proto3" json:"line_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{8}
}

func (x *LogEntry) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *LogEntry) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *LogEntry) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetLineNum() int32 {
	if x != nil {
		return x.LineNum
	}
	return 0
}

type StreamLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      int32                  `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	Processed     int32                  `protobuf:"varint,2,opt,name=processed,proto3" json:"processed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamLogsResponse) Reset() {
	*x = StreamLogsResponse{}
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamLogsResponse) ProtoMessage() {}

func (x *StreamLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_proto_flowforge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamLogsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_proto_flowforge_proto_rawDescGZIP(), []int{9}
}

func (x *StreamLogsResponse) GetReceived() int32 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *StreamLogsResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

var File_pkg_api_proto_flowforge_proto protoreflect.FileDescriptor

const file_pkg_api_proto_flowforge_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/api/proto/flowforge.proto\x12\fflowforge.v1\"\xd5\x01\n" +
	"\x13UpdateStatusRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\"0\n" +
	"\x14UpdateStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"t\n" +
	"\x10SetOutputRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"-\n" +
	"\x11SetOutputResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x83\x01\n" +
	"\x15SaveCheckpointRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"2\n" +
	"\x16SaveCheckpointResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x14GetCheckpointRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\"I\n" +
	"\x15GetCheckpointResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"\xca\x01\n" +
	"\bLogEntry\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x05 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x19\n" +
	"\bline_num\x18\a \x01(\x05R\alineNum\"N\n" +
	"\x12StreamLogsResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x05R\breceived\x12\x1c\n" +
	"\tprocessed\x18\x02 \x01(\x05R\tprocessed2\xb3\x03\n" +
	"\vTaskService\x12U\n" +
	"\fUpdateStatus\x12!.flowforge.v1.UpdateStatusRequest\x1a\".flowforge.v1.UpdateStatusResponse\x12L\n" +
	"\tSetOutput\x12\x1e.flowforge.v1.SetOutputRequest\x1a\x1f.flowforge.v1.SetOutputResponse\x12[\n" +
	"\x0eSaveCheckpoint\x12#.flowforge.v1.SaveCheckpointRequest\x1a$.flowforge.v1.SaveCheckpointResponse\x12X\n" +
	"\rGetCheckpoint\x12\".flowforge.v1.GetCheckpointRequest\x1a#.flowforge.v1.GetCheckpointResponse\x12H\n" +
	"\n" +
	"StreamLogs\x12\x16.flowforge.v1.LogEntry\x1a .flowforge.v1.StreamLogsResponse(\x01B0Z.github.com/flowforge/flowforge/pkg/api/grpc/v1b\x06proto3"

var (
	file_pkg_api_proto_flowforge_proto_rawDescOnce sync.Once
	file_pkg_api_proto_flowforge_proto_rawDescData []byte
)

func file_pkg_api_proto_flowforge_proto_rawDescGZIP() []byte {
	file_pkg_api_proto_flowforge_proto_rawDescOnce.Do(func() {
		file_pkg_api_proto_flowforge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_proto_flowforge_proto_rawDesc), len(file_pkg_api_proto_flowforge_proto_rawDesc)))
	})
	return file_pkg_api_proto_flowforge_proto_rawDescData
}

var file_pkg_api_proto_flowforge_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_api_proto_flowforge_proto_goTypes = []any{
	(*UpdateStatusRequest)(nil),    // 0: flowforge.v1.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),   // 1: flowforge.v1.UpdateStatusResponse
	(*SetOutputRequest)(nil),       // 2: flowforge.v1.SetOutputRequest
	(*SetOutputResponse)(nil),      // 3: flowforge.v1.SetOutputResponse
	(*SaveCheckpointRequest)(nil),  // 4: flowforge.v1.SaveCheckpointRequest
	(*SaveCheckpointResponse)(nil), // 5: flowforge.v1.SaveCheckpointResponse
	(*GetCheckpointRequest)(nil),   // 6: flowforge.v1.GetCheckpointRequest
	(*GetCheckpointResponse)(nil),  // 7: flowforge.v1.GetCheckpointResponse
	(*LogEntry)(nil),               // 8: flowforge.v1.LogEntry
	(*StreamLogsResponse)(nil),     // 9: flowforge.v1.StreamLogsResponse
}
var file_pkg_api_proto_flowforge_proto_depIdxs = []int32{
	0, // 0: flowforge.v1.TaskService.UpdateStatus:input_type -> flowforge.v1.UpdateStatusRequest
	2, // 1: flowforge.v1.TaskService.SetOutput:input_type -> flowforge.v1.SetOutputRequest
	4, // 2: flowforge.v1.TaskService.SaveCheckpoint:input_type -> flowforge.v1.SaveCheckpointRequest
	6, // 3: flowforge.v1.TaskService.GetCheckpoint:input_type -> flowforge.v1.GetCheckpointRequest
	8, // 4: flowforge.v1.TaskService.StreamLogs:input_type -> flowforge.v1.LogEntry
	1, // 5: flowforge.v1.TaskService.UpdateStatus:output_type -> flowforge.v1.UpdateStatusResponse
	3, // 6: flowforge.v1.TaskService.SetOutput:output_type -> flowforge.v1.SetOutputResponse
	5, // 7: flowforge.v1.TaskService.SaveCheckpoint:output_type -> flowforge.v1.SaveCheckpointResponse
	7, // 8: flowforge.v1.TaskService.GetCheckpoint:output_type -> flowforge.v1.GetCheckpointResponse
	9, // 9: flowforge.v1.TaskService.StreamLogs:output_type -> flowforge.v1.StreamLogsResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_proto_flowforge_proto_init() }
func file_pkg_api_proto_flowforge_proto_init() {
	if File_pkg_api_proto_flowforge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_proto_flowforge_proto_rawDesc), len(file_pkg_api_proto_flowforge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_proto_flowforge_proto_goTypes,
		DependencyIndexes: file_pkg_api_proto_flowforge_proto_depIdxs,
		MessageInfos:      file_pkg_api_proto_flowforge_proto_msgTypes,
	}.Build()
	File_pkg_api_proto_flowforge_proto = out.File
	file_pkg_api_proto_flowforge_proto_goTypes = nil
	file_pkg_api_proto_flowforge_proto_depIdxs = nil
}
